### ISSUE TITLE
Wrong css generation with libsass 3.6.3

### ISSUE THREAD

**Issue by cysp74** [nrhodes91/AdMin#8]
Sassc generates from source approx. 70M large css regardless of light/dark version.

This probably related patterns issue described here:
https://github.com/sass/libsass/issues/3033

*:hover {
  *:visited {
    color: green;
  }
}

button {
  @extend *:hover;
}

Similar patterns can be found _common.scss

Cheers.

**Comment by rhodesn** [comment]
@cysp74 thanks for raising this - I'm not sure what I can do about it; 99% of the CSS used in this themes is just straight from [GTK3](https://gitlab.gnome.org/GNOME/gtk/-/tree/master/gtk%2Ftheme%2FAdwaita). I actually just downgraded my libsass package to 3.5.? to avoid several other deprecation warnings and haven't had an issue since.

**Comment by cysp74** [comment]
Perhaps prebuilt packages as releases? However this would increase maintenance activity on your side....

**Comment by rhodesn** [comment]
Thinking about it - I should just include the compiled .css files in the repo just like every other theme developer seems to do. It would be distro/package manager agnostic and would prevent compilation issues due to package updates. I'll see if I can push that up today.

**Comment by rhodesn** [comment]
I've included the compiled CSS that I get in the repo. It should now just be a case of symlinking the directories and re-opening gnome-tweaks to see the themes. Let me know if that's working for you.

**Comment by cysp74** [comment]
Awesome, working as expected on my end, issue can closed, thanks. :)
